Feature/browser support
DEFRA/waste-permits-dynamics-acceptance-tests pull request #2
Opened 2017-09-01 10:09 UTC by timstone

Added logic to select either firefox, chrome or internet explorer as the preferred browser to run the tests on.

2017-09-05 09:22 UTC, timstone commented
@cjibb01 I've changed the logic to choose between running the tests locally (using Chrome) or passing the tests over to Browserstack to run remotely.

Happy to demo.

2017-09-08 09:30 UTC, cjibb01 requested changes
Both Local and BrowserStack tests are working OK. Explicit logout could be added back in as discussed on Slack. Only minor recommendations on code style. Consistent naming conventions would be a good idea.

2017-09-08 13:08 UTC, timstone commented
@cjibb01 ok I've made the discussed amendments, also sorted out the sign out so it's not just waiting a set length of time.

2017-09-08 20:18 UTC, cjibb01 approved these changes

2017-09-11 06:46 UTC, merged